# Generated by Django 3.0.5 on 2020-12-03 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='backup',
        ),
        migrations.RemoveField(
            model_name='page',
            name='canonical',
        ),
        migrations.RemoveField(
            model_name='site',
            name='char_set',
        ),
        migrations.RemoveField(
            model_name='site',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='site',
            name='language',
        ),
        migrations.RemoveField(
            model_name='site',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='site',
            name='logo_caption',
        ),
        migrations.RemoveField(
            model_name='site',
            name='logo_height',
        ),
        migrations.RemoveField(
            model_name='site',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='site',
            name='logo_width',
        ),
        migrations.RemoveField(
            model_name='site',
            name='represents',
        ),
        migrations.RemoveField(
            model_name='site',
            name='search_url',
        ),
        migrations.RemoveField(
            model_name='site',
            name='twitter_card',
        ),
        migrations.RemoveField(
            model_name='site',
            name='twitter_username',
        ),
    ]
